'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Accion
    Public Property IdAccion As Integer
    Public Property IdObjeto As Short
    Public Property IdDato As Nullable(Of Short)
    Public Property Fecha As Date
    Public Property Tipo As String
    Public Property Descripcion As String

    Public Overridable Property ObjetoPropiedad As ObjetoPropiedad

End Class
