'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Clase_Propiedad
    Public Property IDClase As Short
    Public Property IDPropiedad As Short
    Public Property Nombre As String
    Public Property TipoDato As String
    Public Property TipoDato_IDClase As Nullable(Of Short)

    Public Overridable Property Clase As Clase
    Public Overridable Property Clase_Propiedad_Lista As ICollection(Of Clase_Propiedad_Lista) = New HashSet(Of Clase_Propiedad_Lista)

End Class
