'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ClasePropiedadLista
    Public Property IdClase As Short
    Public Property IdPropiedad As Short
    Public Property IdLista As Short
    Public Property Nombre As String
    Public Property EsActivo As Boolean

    Public Overridable Property ClasePropiedad As ClasePropiedad

End Class
