'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Clase_Propiedad_Lista
    Public Property IDClase As Short
    Public Property IDPropiedad As Short
    Public Property IDLista As Short
    Public Property Nombre As String
    Public Property EsActivo As Boolean

    Public Overridable Property Clase_Propiedad As Clase_Propiedad

End Class
