'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CSEstructuraContext
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CSEstructuraContext")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Accion() As DbSet(Of Accion)
    Public Overridable Property Clase() As DbSet(Of Clase)
    Public Overridable Property ClasePropiedad() As DbSet(Of ClasePropiedad)
    Public Overridable Property ClasePropiedadLista() As DbSet(Of ClasePropiedadLista)
    Public Overridable Property Objeto() As DbSet(Of Objeto)
    Public Overridable Property ObjetoPropiedad() As DbSet(Of ObjetoPropiedad)
    Public Overridable Property Parametro() As DbSet(Of Parametro)

End Class
