'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Objeto
    Public Property IdObjeto As Short
    Public Property IdObjetoPadre As Nullable(Of Short)
    Public Property Nombre As String
    Public Property IdClase As Nullable(Of Short)
    Public Property Notas As String
    Public Property EsActivo As Boolean

    Public Overridable Property Clase As Clase
    Public Overridable Property ObjetosHijos As ICollection(Of Objeto) = New HashSet(Of Objeto)
    Public Overridable Property ObjetoPadre As Objeto
    Public Overridable Property ObjetoPropiedades As ICollection(Of ObjetoPropiedad) = New HashSet(Of ObjetoPropiedad)

End Class
