'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Objeto
    Public Property IDObjeto As Short
    Public Property IDObjeto_Padre As Nullable(Of Short)
    Public Property Nombre As String
    Public Property IDClase As Nullable(Of Short)
    Public Property EsActivo As Boolean
    Public Property Notas As String

    Public Overridable Property Accion As ICollection(Of Accion) = New HashSet(Of Accion)
    Public Overridable Property Objeto_Padre As ICollection(Of Objeto) = New HashSet(Of Objeto)
    Public Overridable Property Objeto_Hijos As Objeto
    Public Overridable Property Clase As Clase
    Public Overridable Property Objeto_Propiedades As ICollection(Of Objeto_Propiedad) = New HashSet(Of Objeto_Propiedad)

End Class
