'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ObjetoPropiedad
    Public Property IdObjeto As Short
    Public Property IdPropiedad As Short
    Public Property ValorTexto As String
    Public Property ValorNumeroEntero As Nullable(Of Integer)
    Public Property ValorNumeroDecimal As Nullable(Of Decimal)
    Public Property ValorFechaHora As Nullable(Of Date)
    Public Property ValorSiNo As Nullable(Of Boolean)
    Public Property ValorLista As Nullable(Of Short)

    Public Overridable Property Acciones As ICollection(Of Accion) = New HashSet(Of Accion)
    Public Overridable Property Objeto As Objeto

End Class
