'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Objeto_Propiedad
    Public Property IDObjeto As Short
    Public Property IDPropiedad As Short
    Public Property Valor_Texto As String
    Public Property Valor_NumeroEntero As Nullable(Of Integer)
    Public Property Valor_NumeroDecimal As Nullable(Of Decimal)
    Public Property Valor_FechaHora As Nullable(Of Date)
    Public Property Valor_SiNo As Nullable(Of Boolean)
    Public Property Valor_Lista As Nullable(Of Short)

    Public Overridable Property Accion As ICollection(Of Accion) = New HashSet(Of Accion)
    Public Overridable Property Objeto As Objeto

End Class
